CREATE TABLE IF NOT EXISTS `personalizer_config` (
  `id` int(11) NOT NULL auto_increment,
  `owner` varchar(200) NOT NULL default '',
  `opassword` varchar(100) NOT NULL default '',
  `dbServer` varchar(200) NOT NULL default '',
  `dbName` varchar(200) NOT NULL default '',
  `dbUser` varchar(200) NOT NULL default '',
  `dbPassword` varchar(200) NOT NULL default '',
  `instance` varchar(30) NOT NULL default '',
  `group_table` varchar(255) NOT NULL default 'group',
  `user_table` varchar(255) NOT NULL default 'user',
  `relations_table` varchar(255) NOT NULL default 'relations',
  `instancedata` text NOT NULL,
  `loginScreens` text NOT NULL,
  `realm` varchar(255) NOT NULL default '',
  `defaultLoginScreen` varchar(50) NOT NULL default 'system',
  `directLoginScreen` tinyint(4) NOT NULL default '0',
  `systemMail` varchar(50) NOT NULL default '',
  `passiveLogin` tinyint(4) NOT NULL default '0',
  `cookyExpires` varchar(20) NOT NULL default '30',
  `cookyDomain` varchar(255) NOT NULL default '',
  `std_usersGroupsQuery` varchar(255) NOT NULL default '',
  `std_group_tpl_own` varchar(100) NOT NULL default '',
  `std_groupMemberQuery` varchar(255) NOT NULL default '',
  `interfaces` text NOT NULL,
  `extendeddata` text NOT NULL,
  `logds` varchar(50) NOT NULL default '',
  `recoverySender` varchar(255) NOT NULL default '',
  `tries` tinyint(4) NOT NULL default '0',
  `cron_period` int(11) NOT NULL default '0',
  `cron_last` bigint(20) NOT NULL default '0',
  `cron_id` varchar(255) NOT NULL,
  `std_group_tpl_sub` varchar(255) NOT NULL default '',
  `std_group_frame_sub` varchar(255) NOT NULL default '',
  `std_group_tpl_none` varchar(255) NOT NULL default '',
  `std_group_frame_none` varchar(255) NOT NULL default '',
  `std_group_frame_own` varchar(255) NOT NULL default '',
  `recoveryMail` text NOT NULL,
  `recoveryLinkMail` text NOT NULL,
  `recoverySubject` text NOT NULL,
  `instancemeta` text NOT NULL,
  `stdCutOuts` varchar(255) NOT NULL default '',
  `stdUserFields` varchar(255) NOT NULL default '',
  `triggers` text NOT NULL,
  `language` varchar(10) NOT NULL default 'de',
  `languages` varchar(100) NOT NULL default 'de',
  `workflow` tinyint(4) NOT NULL default '0',
  `logevents` text NOT NULL,
  `errorTracking` text NOT NULL,
  `oldcookies` tinyint(4) NOT NULL default '0',
  `events` text NOT NULL,
  `enable_roles` tinyint(4) NOT NULL default '0',
  `role_table` varchar(255) NOT NULL default 'prs_roles',
  `role_group_rel_table` varchar(255) NOT NULL default 'prs_rel_roles_groups',
  `role_user_rel_table` varchar(255) NOT NULL default 'prs_rel_roles_users',
  `moduleRights` mediumtext NOT NULL,
  `ldapswitch` tinyint(4) NOT NULL default '0',
  `ldap_groupobjectclass` varchar(255) NOT NULL default 'group',
  `ldapconfig` text NOT NULL,
  `httpsLogin` tinyint(4) NOT NULL default '0',
  `httpsUrl` varchar(255) NOT NULL default '',
  `user_application_table` varchar(255) NOT NULL default '',
  `confirmationLoginSender` varchar(255) NOT NULL default '',
  `confirmationLoginSenderName` varchar(255) NOT NULL,
  `confirmationSubject` text NOT NULL,
  `confirmationMail` text NOT NULL,
  `masterPassword` varchar(32) NOT NULL,
  `masterPasswordIPs` text NOT NULL,
  `enforceAccessArea` tinyint(1) NOT NULL default '1',
  `janrainApiKey` varchar(255) NOT NULL,
  `janrainAppName` varchar(255) NOT NULL,
  `janrainAutoSignup` tinyint(1) NOT NULL,
  `janrainAutoGroups` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 PACK_KEYS=1 AUTO_INCREMENT=24 ;