<?php
return array (
  0 => 'CREATE TABLE IF NOT EXISTS `cnt_viewClasses` (',
  1 => '`id` int(11) NOT NULL AUTO_INCREMENT,',
  2 => '`name` varchar(250) NOT NULL DEFAULT \'\',',
  3 => '`description` text NOT NULL,',
  4 => '`nocleanup` tinyint(4) NOT NULL DEFAULT \'0\',',
  5 => '`modified` bigint(14) NOT NULL DEFAULT \'0\',',
  6 => '`displayFrom` varchar(15) NOT NULL DEFAULT \'0\',',
  7 => '`searchable` varchar(30) NOT NULL DEFAULT \'1\',',
  8 => '`author` varchar(250) NOT NULL DEFAULT \'\',',
  9 => '`default_readRights` varchar(30) NOT NULL DEFAULT \'inheritFromViewClass\',',
  10 => '`showTemplateUrl` text NOT NULL,',
  11 => '`onRead` text NOT NULL,',
  12 => '`sortKey` varchar(255) NOT NULL DEFAULT \'\',',
  13 => '`sortMethod` varchar(20) NOT NULL DEFAULT \'SORT_NORMAL, ASC\',',
  14 => '`subcontentHandling` varchar(20) NOT NULL DEFAULT \'parse\',',
  15 => 'PRIMARY KEY (`id`),',
  16 => 'KEY `name` (`name`),',
  17 => 'KEY `nocleanup` (`nocleanup`),',
  18 => 'KEY `sort` (`sortKey`, `sortMethod`),',
  19 => '',
  20 => ') ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=16 ;',
);
